project_name: shannon

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: shannon
    main: ./main.go
    binary: shannon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: shannon
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: yourusername
    name: shannon
  draft: true
  prerelease: auto

brews:
  - name: shannon
    tap:
      owner: yourusername
      name: homebrew-shannon
    folder: Formula
    homepage: "https://github.com/yourusername/shannon"
    description: "Advanced search and analysis tool for Claude conversation exports"
    license: "MIT"
    test: |
      system "#{bin}/shannon", "--version"
    install: |
      bin.install "shannon"

scoop:
  bucket:
    owner: yourusername
    name: scoop-shannon
  homepage: "https://github.com/yourusername/shannon"
  description: "Advanced search and analysis tool for Claude conversation exports"
  license: MIT

nfpms:
  - id: shannon
    package_name: shannon
    vendor: YourName
    homepage: "https://github.com/yourusername/shannon"
    maintainer: "YourName <your@email.com>"
    description: "Advanced search and analysis tool for Claude conversation exports"
    license: MIT
    formats:
      - deb
      - rpm
      - apk